# 1. Changing the csv files' encoding to UTF-8 for text-visualizing purposes

In [ ]:
import pandas as pd

df = pd.read_csv("/content/player_latest_market_value2.csv", encoding="utf-8", low_memory=False)
df.to_csv("player_mv_utf8.csv", index=False, encoding="utf-8")

df.head(5)

   player_id   date_unix  value
0          1  2009-04-22    0.0
1          6  2010-08-01    0.0
2          8  2010-01-01    0.0
3         10  2016-06-30    0.0
4         11  2009-03-18    0.0

In [ ]:
import pandas as pd

df = pd.read_csv("/content/player_profiles2.csv", encoding="utf-8", low_memory=False)
df.to_csv("player_profiles_utf8.csv", index=False, encoding="utf-8")
df.head()

,player_id,player_slug,player_name,player_image_url,name_in_home_country,date_of_birth,place_of_birth,country_of_birth,height,citizenship,...,on_loan_from_club_id,on_loan_from_club_name,contract_there_expires,second_club_url,second_club_name,third_club_url,third_club_name,fourth_club_url,fourth_club_name,date_of_death
0,1,silvio-adzic,Silvio Adzic (1),https://img.a.transfermarkt.technology/portrai...,NaN,1980-09-23,Grünstadt,Germany,0.0,Germany,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,100011,everton-silva,Éverton Silva (100011),https://img.a.transfermarkt.technology/portrai...,Éverton José Modesto da Silva,1988-08-04,São João de Meriti,Brazil,171.0,Brazil,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,10,miroslav-klose,Miroslav Klose (10),https://img.a.transfermarkt.technology/portrai...,Miroslav Josef Klose,1978-06-09,Opole,Germany,184.0,Germany,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,10001,john-thompson,John Thompson (10001),https://img.a.transfermarkt.technology/portrai...,John Paul Thompson,1981-10-12,Dublin,Ireland,183.0,Ireland,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,100001,carlos-auzqui,Carlos Auzqui (100001),https://img.a.transfermarkt.technology/portrai...,Carlos Daniel Auzqui,1991-03-16,Longchamps,Argentina,180.0,Argentina,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Merging dfs to get full profile + market value

In [ ]:
import pandas as pd

# Load data
df_value = pd.read_csv(
    "/content/player_mv_utf8.csv",
    encoding="utf-8",
    low_memory=False
)

df_profiles = pd.read_csv(
    "/content/player_profiles_utf8.csv",
    encoding="utf-8",
    low_memory=False
)

# Keep only what we need from value df
df_value = df_value[["player_id", "value"]]

# Merge
df_merged = df_profiles.merge(
    df_value,
    on="player_id",
    how="left"
)

df_merged.head()

,player_id,player_slug,player_name,player_image_url,name_in_home_country,date_of_birth,place_of_birth,country_of_birth,height,citizenship,...,on_loan_from_club_name,contract_there_expires,second_club_url,second_club_name,third_club_url,third_club_name,fourth_club_url,fourth_club_name,date_of_death,value
0,1,silvio-adzic,Silvio Adzic (1),https://img.a.transfermarkt.technology/portrai...,NaN,1980-09-23,Grünstadt,Germany,0.0,Germany,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1,100011,everton-silva,Éverton Silva (100011),https://img.a.transfermarkt.technology/portrai...,Éverton José Modesto da Silva,1988-08-04,São João de Meriti,Brazil,171.0,Brazil,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2,10,miroslav-klose,Miroslav Klose (10),https://img.a.transfermarkt.technology/portrai...,Miroslav Josef Klose,1978-06-09,Opole,Germany,184.0,Germany,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
3,10001,john-thompson,John Thompson (10001),https://img.a.transfermarkt.technology/portrai...,John Paul Thompson,1981-10-12,Dublin,Ireland,183.0,Ireland,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
4,100001,carlos-auzqui,Carlos Auzqui (100001),https://img.a.transfermarkt.technology/portrai...,Carlos Daniel Auzqui,1991-03-16,Longchamps,Argentina,180.0,Argentina,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,200000.0

# 2. Cleaning the data

Eliminating retired players from the dataset

In [ ]:
df_merged = df_merged[
    df_merged["current_club_name"].notna() &
    ~df_merged["current_club_name"].isin(["Retired", "Unknown"])
]

df_merged.head(10)

,player_id,player_slug,player_name,player_image_url,name_in_home_country,date_of_birth,place_of_birth,country_of_birth,height,citizenship,...,on_loan_from_club_name,contract_there_expires,second_club_url,second_club_name,third_club_url,third_club_name,fourth_club_url,fourth_club_name,date_of_death,value
1,100011,everton-silva,Éverton Silva (100011),https://img.a.transfermarkt.technology/portrai...,Éverton José Modesto da Silva,1988-08-04,São João de Meriti,Brazil,171.0,Brazil,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
4,100001,carlos-auzqui,Carlos Auzqui (100001),https://img.a.transfermarkt.technology/portrai...,Carlos Daniel Auzqui,1991-03-16,Longchamps,Argentina,180.0,Argentina,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,200000.0
6,1000153,matheo-sanchez,Matheo Sánchez (1000153),https://img.a.transfermarkt.technology/portrai...,Matheo Manuel André Sánchez,2003-03-13,Belfort,France,186.0,France,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,100020,sergiy-zagynaylov,Sergiy Zagynaylov (100020),https://img.a.transfermarkt.technology/portrai...,Загинайлов Сергій Геннадійович,1991-01-03,"Brovary, Kyiv Oblast",Ukraine,181.0,Ukraine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
9,1000161,lenny-stoltz,Lenny Stoltz (1000161),https://img.a.transfermarkt.technology/portrai...,Lenny Stoltz Kachouri,2000-06-13,Wissembourg,France,182.0,France Tunisia,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
10,1000253,facundo-canete,Facundo Canete (1000253),https://img.a.transfermarkt.technology/portrai...,NaN,2000-02-22,NaN,NaN,0.0,United States Argentina,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,1000274,brian-romero,Brian Romero (1000274),https://img.a.transfermarkt.technology/portrai...,Brian Carmona Romero,2006-05-11,"Concord, North Carolina",United States,0.0,United States Mexico,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,150000.0
12,1000273,nimfasha-berchimas,Nimfasha Berchimas (1000273),https://img.a.transfermarkt.technology/portrai...,NaN,2008-02-22,NaN,NaN,172.0,United States Burundi,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,400000.0
13,1000148,malcolm-rangon,Malcolm Rangon (1000148),https://img.a.transfermarkt.technology/portrai...,NaN,2004-02-21,Lyon,France,185.0,France Martinique,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,1000150,mauricio-goncalves-da-moura,Mauricio Gonçalves da Moura (1000150),https://img.a.transfermarkt.technology/portrai...,Tefan Mauricio Gonçalves da Moura,2004-06-20,NaN,NaN,178.0,Cape Verde France,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Eliminating non necessary columns

In [ ]:
cols_to_drop = [
    "player_slug",
    "name_in_home_country",
    "place_of_birth",
    "country_of_birth",
    "position",
    "main_position",
    "current_club_id",
    "current_club_name",
    "joined",
    "outfitter",
    "player_agent_id",
    "social_media_url",
    "contract_option",
    "date_of_last_contract_extension",
    "on_loan_from_club_id",
    "on_loan_from_club_name",
    "contract_there_expires",
    "second_club_url",
    "second_club_name",
    "third_club_url",
    "third_club_name",
    "fourth_club_url",
    "fourth_club_name",
    "date_of_death"
]

df_merged = df_merged.drop(columns=cols_to_drop, errors="ignore")

df_merged.head(5)

,player_id,player_name,player_image_url,date_of_birth,height,citizenship,is_eu,foot,contract_expires,player_agent_name,value
1,100011,Éverton Silva (100011),https://img.a.transfermarkt.technology/portrai...,1988-08-04,171.0,Brazil,False,right,NaN,RN Sports,0.0
4,100001,Carlos Auzqui (100001),https://img.a.transfermarkt.technology/portrai...,1991-03-16,180.0,Argentina,False,right,2025-12-31,OLLER GROUP,200000.0
6,1000153,Matheo Sánchez (1000153),https://img.a.transfermarkt.technology/portrai...,2003-03-13,186.0,France,True,right,2026-06-30,NaN,NaN
8,100020,Sergiy Zagynaylov (100020),https://img.a.transfermarkt.technology/portrai...,1991-01-03,181.0,Ukraine,False,left,NaN,NaN,0.0
9,1000161,Lenny Stoltz (1000161),https://img.a.transfermarkt.technology/portrai...,2000-06-13,182.0,France Tunisia,True,left,2028-06-30,BESTWAY SOCCER ...,0.0

Eliminate the ID from the player_name column

In [ ]:
df_merged["player_name"] = df_merged["player_name"].str.replace(
    r"\s*\(\d+\)$", "", regex=True
)

df_merged.head(5)

,player_id,player_name,player_image_url,date_of_birth,height,citizenship,is_eu,foot,contract_expires,player_agent_name,value
1,100011,Éverton Silva,https://img.a.transfermarkt.technology/portrai...,1988-08-04,171.0,Brazil,False,right,NaN,RN Sports,0.0
4,100001,Carlos Auzqui,https://img.a.transfermarkt.technology/portrai...,1991-03-16,180.0,Argentina,False,right,2025-12-31,OLLER GROUP,200000.0
6,1000153,Matheo Sánchez,https://img.a.transfermarkt.technology/portrai...,2003-03-13,186.0,France,True,right,2026-06-30,NaN,NaN
8,100020,Sergiy Zagynaylov,https://img.a.transfermarkt.technology/portrai...,1991-01-03,181.0,Ukraine,False,left,NaN,NaN,0.0
9,1000161,Lenny Stoltz,https://img.a.transfermarkt.technology/portrai...,2000-06-13,182.0,France Tunisia,True,left,2028-06-30,BESTWAY SOCCER ...,0.0

Eliminate players with no registered market value (irrelevant)

In [ ]:
df_merged = df_merged[df_merged["value"].notna() & (df_merged["value"] > 0)]

df_merged.head(5)

,player_id,player_name,player_image_url,date_of_birth,height,citizenship,is_eu,foot,contract_expires,player_agent_name,value
4,100001,Carlos Auzqui,https://img.a.transfermarkt.technology/portrai...,1991-03-16,180.0,Argentina,False,right,2025-12-31,OLLER GROUP,200000.0
11,1000274,Brian Romero,https://img.a.transfermarkt.technology/portrai...,2006-05-11,0.0,United States Mexico,False,NaN,2026-12-31,EL C1EL0,150000.0
12,1000273,Nimfasha Berchimas,https://img.a.transfermarkt.technology/portrai...,2008-02-22,172.0,United States Burundi,False,right,2026-12-31,Agent is known - Player under 18,400000.0
15,1000135,Joselu Pérez,https://img.a.transfermarkt.technology/portrai...,2004-03-12,183.0,Spain,True,right,2027-06-30,GR Soccer,100000.0
16,1000284,Jed Drew,https://img.a.transfermarkt.technology/portrai...,2003-08-29,176.0,Australia,False,right,2028-06-30,Calibre Management,550000.0

In [ ]:
df_merged.to_csv(
    "player_profiles_final.csv",
    index=False,
    encoding="utf-8"
)

# 3. Merging Profiles Dataset with Performance Dataset

First, ensure the correct encoding is applied and replace NaN values for zeroes

In [ ]:
import pandas as pd

df = pd.read_csv(
    "/content/players_data-2024_2025.csv",
    encoding="utf-8",
    low_memory=False
)

df.to_csv(
    "/content/players_data-2024_2025_utf8.csv",
    index=False,
    encoding="utf-8"
)


df = df.fillna(0)

df.head(5)

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,MP,Starts,...,Att (GK),Thr,Launch%,AvgLen,Opp,Stp,Stp%,#OPA,#OPA/90,AvgDist
0,1,Max Aarons,eng ENG,DF,Bournemouth,eng Premier League,24.0,2000.0,3,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,Max Aarons,eng ENG,"DF,MF",Valencia,es La Liga,24.0,2000.0,4,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3,Rodrigo Abajas,es ESP,DF,Valencia,es La Liga,21.0,2003.0,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,James Abankwah,ie IRL,"DF,MF",Udinese,it Serie A,20.0,2004.0,6,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5,Keyliane Abdallah,fr FRA,FW,Marseille,fr Ligue 1,18.0,2006.0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Clean Dataset

The Dataset had many duplicated miscellaneous columns

In [ ]:
cols_to_drop = [
    # Shooting
    "Rk_stats_shooting", "Nation_stats_shooting", "Pos_stats_shooting",
    "Comp_stats_shooting", "Age_stats_shooting", "Born_stats_shooting",
    "90s_stats_shooting", "Gls_stats_shooting",

    # Passing
    "Rk_stats_passing", "Nation_stats_passing", "Pos_stats_passing",
    "Comp_stats_passing", "Age_stats_passing", "Born_stats_passing",
    "90s_stats_passing",

    # Passing types
    "Rk_stats_passing_types", "Nation_stats_passing_types",
    "Pos_stats_passing_types", "Comp_stats_passing_types",
    "Age_stats_passing_types", "Born_stats_passing_types",
    "90s_stats_passing_types",

    # GCA
    "Rk_stats_gca", "Nation_stats_gca", "Pos_stats_gca",
    "Comp_stats_gca", "Age_stats_gca", "Born_stats_gca",
    "90s_stats_gca",

    # Defense
    "Rk_stats_defense", "Nation_stats_defense", "Pos_stats_defense",
    "Comp_stats_defense", "Age_stats_defense", "Born_stats_defense",
    "90s_stats_defense",

    # Possession
    "Rk_stats_possession", "Nation_stats_possession", "Pos_stats_possession",
    "Comp_stats_possession", "Age_stats_possession", "Born_stats_possession",
    "90s_stats_possession",

    # Playing time
    "Rk_stats_playing_time", "Nation_stats_playing_time", "Pos_stats_playing_time",
    "Comp_stats_playing_time", "Age_stats_playing_time", "Born_stats_playing_time",

    # Misc
    "Rk_stats_misc", "Nation_stats_misc", "Pos_stats_misc",
    "Comp_stats_misc", "Age_stats_misc", "Born_stats_misc",
    "90s_stats_misc",

    # Keeper
    "Rk_stats_keeper", "Nation_stats_keeper", "Pos_stats_keeper",
    "Comp_stats_keeper", "Age_stats_keeper", "Born_stats_keeper",
    "MP_stats_keeper",

    # Keeper advanced
    "Rk_stats_keeper_adv", "Nation_stats_keeper_adv", "Pos_stats_keeper_adv",
    "Comp_stats_keeper_adv", "Age_stats_keeper_adv", "Born_stats_keeper_adv",
    "90s_stats_keeper_adv"
]

df = df.drop(columns=cols_to_drop, errors="ignore")

df.head(5)

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,MP,Starts,...,Att (GK),Thr,Launch%,AvgLen,Opp,Stp,Stp%,#OPA,#OPA/90,AvgDist
0,1,Max Aarons,eng ENG,DF,Bournemouth,eng Premier League,24.0,2000.0,3,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,Max Aarons,eng ENG,"DF,MF",Valencia,es La Liga,24.0,2000.0,4,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3,Rodrigo Abajas,es ESP,DF,Valencia,es La Liga,21.0,2003.0,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,James Abankwah,ie IRL,"DF,MF",Udinese,it Serie A,20.0,2004.0,6,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5,Keyliane Abdallah,fr FRA,FW,Marseille,fr Ligue 1,18.0,2006.0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

As we can observe, 80 columns were dropped. This allows a cleaner view of the stats we are interested in.

## Now we merge the datasets.

In [ ]:
from google.colab import files
import pandas as pd

print("Please upload your dataset file:")

Please upload your dataset file:

Saving .player_performance_complete.csv to .player_performance_complete (1).csv
User uploaded file ".player_performance_complete (1).csv" with length 3161948 bytes

ParserError: Error tokenizing data. C error: Expected 1 fields in line 3, saw 2

In [ ]:
!pip install rapidfuzz
import pandas as pd
import numpy as np
import re
import unicodedata

# ------------------------------------------------------------
uploaded = files.upload()

for filename in uploaded.keys():
  print(f'User uploaded file "{filename}" with length {len(uploaded[filename])} bytes')
  df_uploaded = pd.read_csv(filename)
  print(f'Successfully loaded "{filename}" into a DataFrame.')
  display(df_uploaded.head())
# ------------------------------------------------------------

# ---------------------------
# 1) Name normalization utils
# ---------------------------
def normalize_name(x):
    """Lowercase, strip, remove accents, collapse spaces, remove trailing '(digits)'."""
    if not isinstance(x, str):
        return ""
    x = x.strip()
    x = re.sub(r"\s*\(\d+\)\s*$", "", x)
    x = (
        unicodedata.normalize("NFKD", x)
        .encode("ascii", "ignore")
        .decode("utf-8", errors="ignore")
    )
    x = x.lower().strip()
    x = re.sub(r"\s+", " ", x)
    return x

# ---------------------------------------
# 2) Make working copies + normalize names
# ---------------------------------------
df_perf = df.copy()
df_prof = df_merged.copy()

if "Player" not in df_perf.columns:
    raise KeyError("Performance df (df) must contain a 'Player' column.")
if "player_name" not in df_prof.columns:
    raise KeyError("Profiles df (df_merged) must contain a 'player_name' column.")

df_perf["name_norm"] = df_perf["Player"].map(normalize_name)
df_prof["name_norm"] = df_prof["player_name"].map(normalize_name)

df_perf = df_perf[df_perf["name_norm"] != ""].copy()
df_prof = df_prof[df_prof["name_norm"] != ""].copy()

# -----------------------------------------
# 3) Exact merge first
# -----------------------------------------
df_total = df_perf.merge(
    df_prof,
    on="name_norm",
    how="left",
    suffixes=("", "_profile")
)

profile_match_col = "player_id" if "player_id" in df_total.columns else "player_name"
unmatched_mask = df_total[profile_match_col].isna()

# snapshot exact-match count before fuzzy pass
n_exact_matched = int((~unmatched_mask).sum())

# -----------------------------------------
# 4) Fuzzy matching for the unmatched names
# -----------------------------------------
perf_unmatched_names = df_total.loc[unmatched_mask, "name_norm"].unique().tolist()
prof_names = df_prof["name_norm"].unique().tolist()

try:
    from rapidfuzz import process, fuzz

    def best_fuzzy_match(query, choices):
        m = process.extractOne(query, choices, scorer=fuzz.token_set_ratio)
        return (m[0], float(m[1])) if m else (None, 0.0)

except Exception:
    import difflib

    def best_fuzzy_match(query, choices):
        m = difflib.get_close_matches(query, choices, n=1, cutoff=0)
        if not m:
            return (None, 0.0)
        score = difflib.SequenceMatcher(None, query, m[0]).ratio() * 100.0
        return (m[0], float(score))

THRESHOLD = 90.0

mapping = {}
scores = {}

for q in perf_unmatched_names:
    m, s = best_fuzzy_match(q, prof_names)
    if m is not None and s >= THRESHOLD:
        mapping[q] = m
        scores[q] = s

df_total["name_norm_fuzzy"] = df_total["name_norm"]
df_total.loc[unmatched_mask, "name_norm_fuzzy"] = (
    df_total.loc[unmatched_mask, "name_norm"].map(mapping).fillna(df_total.loc[unmatched_mask, "name_norm"])
)

df_total["fuzzy_matched"] = False
df_total.loc[unmatched_mask, "fuzzy_matched"] = df_total.loc[unmatched_mask, "name_norm"].isin(mapping.keys())

df_total["fuzzy_score"] = np.nan
df_total.loc[unmatched_mask, "fuzzy_score"] = df_total.loc[unmatched_mask, "name_norm"].map(scores)

prof_cols_to_add = [c for c in df_prof.columns if c not in ("name_norm",)]
df_prof_for_merge = df_prof.rename(columns={"name_norm": "name_norm_fuzzy"})

df_total = df_total.merge(
    df_prof_for_merge[["name_norm_fuzzy"] + prof_cols_to_add],
    on="name_norm_fuzzy",
    how="left",
    suffixes=("", "_fuzzy")
)

for col in df_prof.columns:
    if col in ("name_norm",):
        continue
    fuzzy_col = f"{col}_fuzzy"
    if fuzzy_col in df_total.columns and col in df_total.columns:
        df_total[col] = df_total[col].combine_first(df_total[fuzzy_col])

drop_fuzzy_dupes = [c for c in df_total.columns if c.endswith("_fuzzy")]
df_total = df_total.drop(columns=drop_fuzzy_dupes, errors="ignore")

# -----------------------------------------
# 5) MATCH DIAGNOSTICS  ← INSERT FOR THESIS
# -----------------------------------------
total_records   = len(df_total)
n_fuzzy_matched = int(df_total["fuzzy_matched"].sum())
total_matched   = n_exact_matched + n_fuzzy_matched
total_unmatched = int(df_total[profile_match_col].isna().sum())
match_rate      = total_matched / total_records * 100

fuzzy_scores_series = df_total.loc[df_total["fuzzy_matched"], "fuzzy_score"]
avg_fuzzy_score = fuzzy_scores_series.mean()
min_fuzzy_score = fuzzy_scores_series.min()

print("=" * 57)
print("       RAPIDFUZZ MERGE — MATCH DIAGNOSTICS")
print("=" * 57)
print(f"  Total performance records       : {total_records:,}")
print(f"  Exact matches  (FBRef ↔ TM)    : {n_exact_matched:,}")
print(f"  Fuzzy matches  (score ≥ {THRESHOLD:.0f})     : {n_fuzzy_matched:,}")
print(f"  ───────────────────────────────────────────")
print(f"  Total matched                   : {total_matched:,}")
print(f"  Unmatched (no profile found)    : {total_unmatched:,}")
print(f"  Overall match rate              : {match_rate:.1f}%")
print(f"  ───────────────────────────────────────────")
if n_fuzzy_matched > 0:
    print(f"  Avg fuzzy score (matched rows)  : {avg_fuzzy_score:.1f} / 100")
    print(f"  Min fuzzy score accepted        : {min_fuzzy_score:.1f} / 100")
print("=" * 57)

# Sample of unmatched names for manual audit
unmatched_sample = (
    df_total.loc[df_total[profile_match_col].isna(), "Player"]
    .dropna().unique()[:10]

)
if len(unmatched_sample):
    print("\n  Sample unmatched names (first 10):")
    for name in unmatched_sample:
        print(f"    · {name}")

# -----------------------------------------
# 6) Save final dataset
# -----------------------------------------
out_path = "/content/df_total.csv"
df_total.to_csv(out_path, index=False, encoding="utf-8")

out_path

Requirement already satisfied: rapidfuzz in /usr/local/lib/python3.12/dist-packages (3.14.3)

Saving .player_performance_complete.csv to .player_performance_complete (2).csv
User uploaded file ".player_performance_complete (2).csv" with length 3161948 bytes

ParserError: Error tokenizing data. C error: Expected 1 fields in line 3, saw 2

In [ ]:
# ─────────────────────────────────────────────────────────────────
# MATCH DIAGNOSTICS — run this cell immediately after the RapidFuzz
# merge cell (Cell 22) to retrieve the stats needed for the thesis.
# ─────────────────────────────────────────────────────────────────
import pandas as pd

# ── 1. Total records in the performance dataframe ────────────────
total_records = len(df_total)

# ── 2. Exact matches (profile joined, not via fuzzy) ─────────────
# A row was exact-matched if player_id is populated AND fuzzy_matched is False
exact_matched = int(
    (df_total["player_id"].notna() & ~df_total["fuzzy_matched"]).sum()
)

# ── 3. Fuzzy matches (RapidFuzz, score ≥ 90) ─────────────────────
fuzzy_matched = int(df_total["fuzzy_matched"].sum())

# ── 4. Total matched (exact + fuzzy) ─────────────────────────────
total_matched = exact_matched + fuzzy_matched

# ── 5. Unmatched (no profile found at all) ───────────────────────
total_unmatched = int(df_total["player_id"].isna().sum())

# ── 6. Overall match rate ─────────────────────────────────────────
match_rate = total_matched / total_records * 100

# ── 7. Fuzzy score distribution (among fuzzy-matched rows) ────────
fuzzy_scores = df_total.loc[df_total["fuzzy_matched"], "fuzzy_score"]
avg_fuzzy_score  = fuzzy_scores.mean()
min_fuzzy_score  = fuzzy_scores.min()

# ─────────────────────────────────────────────────────────────────
print("=" * 55)
print("         RAPIDFUZZ MERGE — DIAGNOSTICS REPORT")
print("=" * 55)
print(f"  Total performance records      : {total_records:,}")
print(f"  Exact matches                  : {exact_matched:,}")
print(f"  Fuzzy matches  (score ≥ 90)    : {fuzzy_matched:,}")
print(f"  ─────────────────────────────────────────")
print(f"  Total matched                  : {total_matched:,}")
print(f"  Unmatched                      : {total_unmatched:,}")
print(f"  Overall match rate             : {match_rate:.1f}%")
print(f"  ─────────────────────────────────────────")
print(f"  Avg fuzzy score (matched)      : {avg_fuzzy_score:.1f}")
print(f"  Min fuzzy score accepted       : {min_fuzzy_score:.1f}")
print("=" * 55)

# ── 8. Sample unmatched names (for manual audit) ─────────────────
unmatched_names = (
    df_total.loc[df_total["player_id"].isna(), "Player"]
    .dropna()
    .unique()[:15]
)
print("\n  Sample unmatched player names (first 15):")
for name in unmatched_names:
    print(f"    · {name}")